# http://www.appveyor.com/docs/appveyor-yml

version: 1.0.1.{build}
configuration: Release

build_script:
  - powershell ./build.ps1 -Target CI

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

artifacts:
  - path: Publish\**\*.nupkg
    name: NuGet

  - path: Publish\**\*.zip
    name: zip