# http://www.appveyor.com/docs/appveyor-yml

version: 1.0.1.{build}
configuration: Release

init:
  - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version.Replace("-dev$env:appveyor_build_number", "-dev"))$($env:appveyor_build_number.PadLeft(4, '0'))"

# Install scripts. (runs after repo cloning)
install:
  - nuget restore

build_script:
  - ./build.ps1 -Target CI

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

artifacts:
  - path: Publish\**\*.nupkg
    name: NuGet

  - path: Publish\**\*.zip
    name: zip